currency_converter/forms.py
from wtforms import Form, FloatField, SelectField, validators


class ConvertForm(Form):

    amount = FloatField('Amount', [validators.InputRequired(),
                                   validators.NumberRange(min=0, max=10000)])
    convert_from = SelectField('From', choices=[])
    convert_to = SelectField('To', choices=[])

currency_converter/app.py
from flask import Flask
from flask_redis import Redis

redis_store = Redis()


def create_app():
    app = Flask(__name__)
    app.config.from_object('currency_converter.appconfig.Config')

    redis_store.init_app(app)

    # register all pages
    from views.converter import converter_page

    app.register_blueprint(converter_page)

    return app

currency_converter/views/converter.py
from decimal import Decimal

from flask import Blueprint, render_template, request

from currency_converter.forms import ConvertForm
from currency_converter.app import redis_store

converter_page = Blueprint('converter', __name__)

BASE_CURRENCY = 'RUB'


@converter_page.route('/', methods=['GET', 'POST'])
def index():
    form = ConvertForm(request.form)

    # it's a bad way to cache all available currencies. But it's ok for this
    # example
    currency_choices = redis_store.keys('*') or []
    currency_choices = [(c, c) for c in sorted(currency_choices)]
    currency_choices.insert(0, (BASE_CURRENCY, BASE_CURRENCY))
    form.convert_from.choices = currency_choices
    form.convert_to.choices = currency_choices

    result = None
    if request.method == 'POST' and form.validate():
        from_currency = form.convert_from.data.upper()
        to_currency = form.convert_to.data.upper()
        amount = Decimal(form.amount.data)

        if from_currency == to_currency:
            result = amount
        else:
            base_amount = amount
            if from_currency != BASE_CURRENCY:
                from_currency_data = redis_store.hgetall(from_currency)
                base_amount = amount * Decimal(from_currency_data['rate'])

            rate = Decimal(1.0)
            if to_currency != BASE_CURRENCY:
                to_currency_data = redis_store.hgetall(to_currency)
                rate = rate / Decimal(to_currency_data['rate'])

            result = base_amount * rate
            result = result.quantize(Decimal('.0000'))

    return render_template('index.html', form=form, result=result)

currency_converter/templates/_formhelpers.html
{% macro render_field(field) %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
        {{ field.label(class_="control-label col-sm-2") }}
        <div class="col-sm-2">
            {{ field(class_="form-control", **kwargs)|safe }}
            {% if field.errors %}
                <p class="help-block {{ field.name }}-error">{{ field.errors|join(' ') }}</p>
            {% endif %}
            {% if field.description %}
                <p class="help-block">{{ field.description }}</p>
            {% endif %}
        </div>
    </div>
{% endmacro %}

currency_converter/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Currency Converter</title>
  </head>
  <body>
    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% from "_formhelpers.html" import render_field %}
    <div class="container">
      <div class="page-header"><h1>Currency Converter<h1></div>
      <form method="POST" action="{{ url_for('converter.index') }}" class="form-horizontal" role="form">
        {{ form.csrf_token }}
        {{ render_field(form.amount) }}
        {{ render_field(form.convert_from) }}
        {{ render_field(form.convert_to) }}
        {% if result %}
        <div class="form-group">
            <label class="col-sm-2 control-label">Result</label>
            <div class="col-sm-10">
            <p class="form-control-static" id="result">{{ result }}</p>
            </div>
        </div>
        {% endif %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Convert</button>
          </div>
        </div>
      </form>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  </body>
</html>